### ISSUE TITLE
Can't get it to work, nonetheless something happen when I execute the script

### ISSUE THREAD

**Issue by lucientisserand** [capn-damo/Openbox-tiling#1]
Dear Damo, I really like this hack in order to get tiling buttons on my tint2.

Currently running on debian buster with helium configs (well, I did the upgrade before the new release...), having wmctrl and xdotool installed.

I followed the steps of your installation.
When I press a button, temp files are created and I can see that all my windows (I tested with four instances of pcmanfm) are consecutively focused on tint2 panel (but not on the desktop) but no tiling happen.
I tried to run the script in a terminal with the three different parameters, nothing shows up. On the second run, when it is supposed to restore positions and sizes, there is only the wmctrl output like this : 
> 2,6d1
> < wmctrl -ir 0x04000007 -e 0,2011,74,680,535
> < wmctrl -ir 0x03a0fd3b -e 0,2199,0,1079,687
> < wmctrl -ir 0x03a0fde0 -e 0,1600,316,1079,687
> < wmctrl -ir 0x03a0fe8d -e 0,2199,316,1079,687
> < wmctrl -ir 0x03a0ff3c -e 0,1600,0,1079,687
> 2,6d1
> < wmctrl -ir 0x04000007 -e 0,2011,74,680,535
> < wmctrl -ir 0x03a0fd3b -e 0,2199,0,1079,687
> < wmctrl -ir 0x03a0fde0 -e 0,1600,316,1079,687
> < wmctrl -ir 0x03a0fe8d -e 0,2199,316,1079,687
> < wmctrl -ir 0x03a0ff3c -e 0,1600,0,1079,687

And also the "temp-windims.tmp" file is removed on the second run as (I guess) it is supposed to work.
I really wonder what would be the problem... If you have some time to get into it
Thanks for your work on bunsenlabs, former crunchbang user here !

**Comment by capn-damo** [comment]
It is still working on my system, although I haven't looked at the code for a long time :/
Sometimes it takes a couple of goes initially, to get the windows to move.

First thing, are you using ``ob-tile.sh [arg]`` to tile/untile the windows?;

Next, are you using ``rc.xml`` with the tiling keybinds, or have you upgraded to the more recent Bunsenlabs ``bl-rc.xml`` and not added all the keybinds? Make sure that there isn't a keybind already set, which is clashing with the tiling keybinds.

I also found a possible bug, where the ``winlist-XXXX`` files aren't deleted. Try moving ``rm "$TMP_WIN_LIST"`` from the penultimate line, to ``line 214``

**Comment by lucientisserand** [comment]
Okay, I had a second look at my `rc.xml` (it might be 4 years old) and I found the problem, it was my mistake, I just copy-pasted the content of the `wdotool-keybind.xml` at the end of my `rc.xml`  file for conveniency and never realized there was actually a `<keyboard>` section dedicated... Although I changed my keybinds so many times... I moved the keybinds with his other fellow keybinds in the right section and now it works, so cool !
(Although I don't really understand how it behaves with dual monitors and buttons on each monitor panel)

I did move the line you mentioned, just in case.

**Comment by capn-damo** [comment]
The script should detect the current monitor, and only tile the windows there. I use a second hiding tint2 panel on my secondary monitor for that. Please don't ask me to rewrite the script to tile all windows on all monitors at the same time!


---- On Wed, 26 Feb 2020 13:44:58 +0000 lucientisserand <notifications@github.com> wrote ----


Okay, I had a second look at my rc.xml (it might be 4 years old) and I found the problem, it was my mistake, I just copy-pasted the content of the wdotool-keybind.xml at the end of my rc.xml file for conveniency and never realized there was actually a <keyboard> section dedicated... Altough I changed my keybinds so many times... I moved the keybinds with his other fellow keybinds in the right section and now it works, so cool !
 (Altough I don't really understand how it behaves with dual monitors and buttons on each monitor panel)
I did move the line you mentioned, just in case.
